# Generated by Django 4.0.2 on 2022-02-14 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='category parent'),
        ),
        migrations.CreateModel(
            name='Alterative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternatives', models.ManyToManyField(related_name='alterative_products', to='product.Product', verbose_name='alternatives')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='product.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Alterative',
                'verbose_name_plural': 'Alteratives',
            },
        ),
    ]
