# Generated by Django 4.0.2 on 2022-02-14 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_category_parent_alterative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessories', models.ManyToManyField(related_name='product_accesspries', to='product.Product', verbose_name='accesspries')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_main', to='product.product', verbose_name='product ')),
            ],
            options={
                'verbose_name': 'Accessories',
                'verbose_name_plural': 'Accessoriess',
            },
        ),
    ]
