# Generated by Django 4.0.2 on 2022-02-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_accessories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='accessories',
            field=models.ManyToManyField(related_name='product_accessories', to='product.Product', verbose_name='accesspries'),
        ),
    ]
