# Generated by Django 3.2.9 on 2022-02-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Discountprice',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Discountprice'),
            preserve_default=False,
        ),
    ]
