# Generated by Django 4.0.2 on 2022-02-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='desc'),
        ),
    ]
